version: "2"
services:
  flask:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./app:/app"
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ : Asia/Tokyo
    command: python3 /app/app.py