version: "2"
services:
  flask:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./.aws:/home/flaskapp/.aws"
      - "./app:/home/flaskapp/app"

    user: "flaskapp:flaskapp"
    tty: true
    environment:
      TZ : Asia/Tokyo
    command: bin/bash