version: "2"
services:
  flask:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./app:/app"
      - "~/.aws:/home/flaskapp/.aws"
    user:"flaskapp:flaskapp"
    tty: true
    environment:
      TZ : Asia/Tokyo
    command: bin/bash